CREATE TABLE DEPARTMENT (DNO int , DNAME VARCHAR (20), MgrSSN VARCHAR(20),MGRSTARTDATE VARCHAR(20));

INSERT INTO DEPARTMENT VALUES (1,'ACCOUNTS','RNSACC02','01-jan-19'); 
INSERT INTO DEPARTMENT VALUES (2,'IT','RNSIT01','01-AUG-16'); 
INSERT INTO DEPARTMENT VALUES (3,'ECE','RNSECE01','01-JUN-08'); 
INSERT INTO DEPARTMENT VALUES (4,'ISE','RNSISE01','01-AUG-15'); 
INSERT INTO DEPARTMENT VALUES (5,'CSE','RNSCSE05','01-MAY-02');
INSERT INTO DEPARTMENT VALUES (6,'EVS','RNSCSE03','10-JUN-08');
INSERT INTO DEPARTMENT VALUES (7,'WBP','RNSCSE03','01-JULY-07');
INSERT INTO DEPARTMENT VALUES (8,'AM','RNSCSE06','06-APR-05');
INSERT INTO DEPARTMENT VALUES (9,'DBMS','RNSCSE07','03-JUN-03');
INSERT INTO DEPARTMENT VALUES (10,'DSA','RNSCSE08','08-MAY-05');
SELECT *from department;
